I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 396, in script
    mysefl "(Je pensais que ce serait plus animé...)"
Exception: Sayer 'mysefl' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 396, in script
    mysefl "(Je pensais que ce serait plus animé...)"
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mysefl' is not defined.

macOS-14.3-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Cyber Soap 0.1 Development Build
Sat Feb 17 12:31:37 2024
