I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 57, in script
    call screen news_app
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: DynamicImage 'gui/scrollbar/vertical_[prefix_]bar2.png': could not find image. ('gui/scrollbar/vertical_insensitive_bar2.png', 'gui/scrollbar/vertical_bar2.png', and 1 more.)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 57, in script
    call screen news_app
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 2259, in execute
    self.call("execute")
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/exports.py", line 3347, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 4055, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/screen.py", line 481, in visit_all
    self.child.visit_all(callback, seen=None)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 2 more times]
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 674, in visit_all
    for d in self.visit():
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/image.py", line 785, in visit
    self.find_target()
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/display/image.py", line 683, in find_target
    raise Exception(error)
Exception: DynamicImage 'gui/scrollbar/vertical_[prefix_]bar2.png': could not find image. ('gui/scrollbar/vertical_insensitive_bar2.png', 'gui/scrollbar/vertical_bar2.png', and 1 more.)

macOS-14.3-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Cyber Soap 0.1 Development Build
Wed Jan 31 11:00:32 2024
